services:
  traefik:
    image: "traefik:v3.1.4"
    ports:
      - "9080:80"
      - "8080:8080"
    volumes:
      - "./traefik-config.yml:/etc/traefik/traefik.yml:ro"
      - "./http.yml:/etc/traefik/configs/http.yml:ro"
      - ".:/plugins-local/src/github.com/sevensolutions/traefik-oidc-auth:ro"
    env_file:
      - ./.env

  whoami:
    image: "traefik/whoami:latest"
